name = "Dragons Dynamo"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f067a20522171bec4f9db2266f507f6eda16839d2d7d0f44958b8b31e5865abe"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
