name = "Dragons Dynamo"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21556a9a5f35a28ec61bb0bb3c5fdd3be99062264ede79c2b9a3191e2806561d"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
