name = "Dragons Dynamo"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d81e32d187daa10c40fc359d4f1f222e4817f0713dd4fca19cb098d78d21250"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
